# Word Replace Version 3.0
# Changing Word1 -> Word2 since 2011 (Not that long)

#The color of chat after the replaced word
normal-chat-color: WHITE

#The number of word lists(VERY IMPORTANT)
number-of-lists: 2

# A list of List<String> values that go in this order:
#  - WordColor,Word2,Words:To:Be:Replaced
# no spaces, there are two examples below

replaceList: 
- AQUA,Admin,dcsiira:dc:siira
- RED,Almighty God,Notch:Marcus:God

# The First Example replaces the words "dcsiira", "dc", and "siira" with admin colored AQUA