# Word Replace Version 5.0
# Changing Word1 -> Word2 since 2011 (Not that long)

# Supported colors are: (case insensitive)
# - Black(&0)             Dark_Gray(&8)
# - Dark_Blue(&1)         Blue(&9)
# - Dark_Green(&2)        Green(&a)
# - Dark_Aqua(&3)         Aqua(&b)
# - Dark_Red(&4)          Red(&c)
# - Dark_Purple(&5)       Light_Purple(&d)
# - Gold(&6)              Yellow(&e)
# - Gray(&7)              White(&f)
# - You can also use Pink for Light_Purple
# This defaults to WHITE if it finds an error

# An Example is "AQUA,Admin,dcsiira:dc:siira"
# Which replaces the words "dc","dcsiira","siira" with "Admin", Colored in AQUA

normal-chat-color: WHITE
word-replace-list:
- AQUA,Admin,dcsiira:dc:siira
- RED,Notch,Maker:Notch:xNotch
