# Word Replace Version 2.0
# Changing Word1 -> Word2 since 2011 (Not that long)

#The color of chat after the replaced word
normal-chat-color: WHITE

# The word that other words will be changed to, as in Word2
replace-words-to: Admin

# The list or words in single qoutes that will be replaced, as in Word1
replace-these-words: ['DCSiira', 'DC' , 'Siira']

# The resulting color of Word2
replaceWordColor: AQUA