name: WordReplace
main: dcsiira.wordreplace.WordReplace
version: 2.0
commands:
  WR:
    description: States the version of the plugin or reloads the confiq
    usage: |
            /WR [Reload | Version | List]